import type { Metadata } from "next";
import localFont from "next/font/local";


import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import RtlProvider from "@/providers/rtl-provider";
import NextTopLoader from "nextjs-toploader";

const iranSansXFont = localFont({
  src: [
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-Thin.woff", weight: "100" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-Light.woff", weight: "300" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-Medium.woff", weight: "500" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-Regular.woff", weight: "400" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-DemiBold.woff", weight: "600" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-Bold.woff", weight: "700" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-ExtraBold.woff", weight: "800" },
    { path: "../../public/fonts/IranSansX/IRANSansXFaNum-Black.woff", weight: "900" },
  ],
  variable: "--font-iranSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl" className={`${iranSansXFont.variable} font-iranSans`}>
      <body>
      <NextTopLoader showSpinner={false} color='#11161a' />
        <AppRouterCacheProvider>
          <RtlProvider>
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </RtlProvider>
        </AppRouterCacheProvider>

      </body>
    </html>
  );
}
